http:
  port: ${TEST_GW_PORT:-8080}
apiEndpoints:
  api:
    host: '*'
    paths: '/api/v1/*'
serviceEndpoints:
  httpbin:
    url: 'http://localhost:${TEST_BACKEND_PORT:-8081}'
policies:
  - proxy
  - requestid
pipelines:
  - name: basic
    apiEndpoints:
      - api
    policies:
      - requestid:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
